cukinia_symlink: prevent false positives on non-symlinks
After improving the test coverage in the previous commit, I noticed
cukinia_symlink would PASS when inverting the symlink and its
destination arguments, because 'readlink -f' works fine on regular
files as well.

Considering we validate symlinks, make sure the first argument is
actually one before reading its destination.

diff --git a/cukinia b/cukinia
--- a/cukinia
+++ b/cukinia
@@ -506,7 +506,12 @@ _cukinia_symlink()
 {
 	local link="$1"
 	local target="$2"
+
 	_cukinia_prepare "Checking link \"$link\" does ${__not:+NOT }point to \"$target\""
+
+	# fail on non-symlinks
+	[ -L "$link" ] || return 1
+
 	[ "$(readlink -f "$link")" = "$(readlink -f "$target")" ] && return 0 || return 1
 }
 
